format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#89B4FA"  # Catppuccin Mocha "Blue"

[character]
success_symbol = "[❯](#A6E3A1)"  # Catppuccin Mocha "Green"
error_symbol   = "[❯](#F38BA8)"  # Catppuccin Mocha "Red"
vimcmd_symbol  = "[❮](#CBA6F7)"  # Catppuccin Mocha "Mauve"

[git_branch]
format = "[$branch]($style)"
style = "#B4BEFE"  # Catppuccin Mocha "Lavender"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#F38BA8) ($ahead_behind$stashed)]($style)"
style = "#94E2D5"   # Catppuccin Mocha "Teal"
conflicted = "​"
untracked  = "​"
modified   = "​"
staged     = "​"
renamed    = "​"
deleted    = "​"
stashed    = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#B4BEFE"

[cmd_duration]
format = "[$duration]($style) "
style = "#FAB387"   # Catppuccin Mocha "Peach"

[python]
format = "[$virtualenv]($style) "
style = "#CBA6F7"   # Catppuccin Mocha "Mauve"

